OPTION EXPLICIT
CONST W% = MM.HRES
CONST BLOCK_ROWS% = 5
CONST BLOCK_COLS% = 8
DIM INTEGER blocks%(BLOCK_ROWS%-1, BLOCK_COLS%-1)
DIM INTEGER score%

SUB BeepServe(): PLAY TONE 700,700 : PAUSE 40 : PLAY STOP : END SUB

score% = 0
PRINT "Before beep"
BeepServe
PRINT "Done"
END
