' FRAMEBUFFER basic merge path
OPTION EXPLICIT

CLS RGB(BLACK)
FRAMEBUFFER CREATE
FRAMEBUFFER LAYER RGB(BLACK)

FRAMEBUFFER WRITE F
CLS RGB(BLUE)
BOX 20,20,60,30,0,,RGB(GREEN)

FRAMEBUFFER WRITE L
BOX 35,28,20,12,0,,RGB(RED)

FRAMEBUFFER MERGE RGB(BLACK)
FRAMEBUFFER CLOSE

PRINT "done"
