' FRAMEBUFFER running merge path
OPTION EXPLICIT

CLS RGB(BLACK)
FRAMEBUFFER CREATE
FRAMEBUFFER LAYER RGB(BLACK)

FRAMEBUFFER WRITE F
CLS RGB(BLUE)
BOX 12,12,80,40,0,,RGB(GREEN)

FRAMEBUFFER WRITE L
FRAMEBUFFER MERGE RGB(BLACK), R, 1
BOX 30,22,18,18,0,,RGB(RED)
PAUSE 5
FRAMEBUFFER SYNC
FRAMEBUFFER MERGE RGB(BLACK), A
FRAMEBUFFER CLOSE

PRINT "done"
