' FRAMEBUFFER COPY F->L->N
CLS RGB(BLACK)
FRAMEBUFFER CREATE
FRAMEBUFFER LAYER RGB(BLACK)
FRAMEBUFFER WRITE F
BOX 0, 0, 31, 23, 1, RGB(RED), RGB(RED)
FRAMEBUFFER COPY F, L
FRAMEBUFFER WRITE N
CLS RGB(BLACK)
FRAMEBUFFER COPY L, N
PRINT "done"

