' FRAMEBUFFER COPY F->N background then sync
CLS RGB(BLACK)
FRAMEBUFFER CREATE
FRAMEBUFFER WRITE F
BOX 0, 0, 31, 23, 1, RGB(GREEN), RGB(GREEN)
FRAMEBUFFER WRITE N
CLS RGB(BLACK)
FRAMEBUFFER COPY F, N, B
FRAMEBUFFER SYNC
PRINT "done"

