' FRAMEBUFFER CREATE FAST - verify FAST flag parses and merge works
OPTION EXPLICIT

CLS RGB(BLACK)
FRAMEBUFFER CREATE FAST
FRAMEBUFFER LAYER RGB(BLACK)

FRAMEBUFFER WRITE F
CLS RGB(BLUE)
BOX 20,20,60,30,0,,RGB(GREEN)

FRAMEBUFFER WRITE L
BOX 35,28,20,12,0,,RGB(RED)

FRAMEBUFFER MERGE RGB(BLACK)
FRAMEBUFFER CLOSE

' Same test as t159 but with FAST flag - results should be identical
PRINT "done"
