OPTION EXPLICIT

CLS RGB(BLACK)
TEXT 10, 10, "L", "LT", , , RGB(WHITE), RGB(BLACK)
TEXT 60, 20, "C", "CT", , , RGB(GREEN), RGB(BLACK)
TEXT 110, 20, "R", "RT", , , RGB(BLUE), RGB(BLACK)

PRINT "done"
END
