/*
 * drivers/web_console/web_console_assets.c
 *
 * Target-clean static page for the device web console.
 */

#include "web_console_assets.h"

#include <string.h>

static const char index_html[] =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>MMBasic Web Console</title>\n"
"<link rel=\"stylesheet\" href=\"/__web_console/style.css\">\n"
"</head>\n"
"<body>\n"
"<main>\n"
"<div id=\"status\">connecting</div>\n"
"<canvas id=\"display\" width=\"320\" height=\"240\" tabindex=\"0\" aria-label=\"MMBasic display\"></canvas>\n"
"</main>\n"
"<script src=\"/__web_console/app.js\"></script>\n"
"</body>\n"
"</html>\n";

static const char style_css[] =
"html,body{margin:0;min-height:100%;background:#101214;color:#d8dee9;"
"font:14px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}"
"body{display:grid;place-items:center;padding:18px;box-sizing:border-box}"
"main{width:min(100%,720px);display:grid;gap:10px}"
"#display{width:100%;max-width:640px;aspect-ratio:4/3;image-rendering:pixelated;"
"background:#000;border:1px solid #3a4048}"
"#display:focus{outline:2px solid #61afef;outline-offset:3px}"
"#status{color:#e5c07b}"
"#status.ok{color:#98c379}"
"#status.err{color:#e06c75}"
"@media(max-width:900px){body{place-items:start center}}\n";

static const char app_js[] =
"(() => {\n"
"  const status = document.getElementById('status');\n"
"  const canvas = document.getElementById('display');\n"
"  const ctx = canvas.getContext('2d', {alpha:false});\n"
"  let ws;\n"
"  let fbImage = null;\n"
"  let fb = null;\n"
"  let fb32 = null;\n"
"  let flushPending = false;\n"
"  let stats = {FRMB:0, CMDS:0, bytes:0, frames:0};\n"
"  let pendingFlushes = 0;\n"
"  const debugEnabled = location.search.indexOf('debug=1') >= 0;\n"
"  const rgb332Words = new Uint32Array(256);\n"
"  for (let i = 0; i < 256; i++) {\n"
"    const r = Math.round(((i >> 5) & 7) * 255 / 7);\n"
"    const g = Math.round(((i >> 2) & 7) * 255 / 7);\n"
"    const b = Math.round((i & 3) * 255 / 3);\n"
"    rgb332Words[i] = (255 << 24) | (b << 16) | (g << 8) | r;\n"
"  }\n"
"  const specialKeys = {Backspace:8,Tab:9,Enter:13,Escape:27,Delete:127,ArrowUp:128,ArrowDown:129,ArrowLeft:130,ArrowRight:131,Insert:132,Home:134,End:135,PageUp:136,PageDown:137,F1:145,F2:146,F3:147,F4:148,F5:149,F6:150,F7:151,F8:152,F9:153,F10:154,F11:155,F12:156};\n"
"  function note(text, cls) { status.textContent = text; status.className = cls || ''; }\n"
"  function append(text) { if (debugEnabled && window.console && console.debug) console.debug('[web-console]', text); }\n"
"  function debug(text) { if (debugEnabled && window.console && console.log) console.log('[web-console] ' + text); }\n"
"  function rgbWord(rgb) { return (255 << 24) | ((rgb & 255) << 16) | (rgb & 0xff00) | ((rgb >> 16) & 255); }\n"
"  function ensureSize(w, h) {\n"
"    if (w && h && (canvas.width !== w || canvas.height !== h)) {\n"
"      canvas.width = w; canvas.height = h;\n"
"    }\n"
"    if (w && h && (!fbImage || fbImage.width !== w || fbImage.height !== h)) {\n"
"      fbImage = new ImageData(w, h);\n"
"      fb = fbImage.data;\n"
"      fb32 = new Uint32Array(fb.buffer);\n"
"      debug('canvas ' + w + 'x' + h);\n"
"    }\n"
"  }\n"
"  function flushDisplay() {\n"
"    flushPending = false;\n"
"    if (fbImage) {\n"
"      const t = performance.now();\n"
"      ctx.putImageData(fbImage, 0, 0);\n"
"      debug('flush putImageData=' + (performance.now() - t).toFixed(2) + 'ms coalesced=' + pendingFlushes);\n"
"      pendingFlushes = 0;\n"
"    }\n"
"  }\n"
"  function scheduleFlush() {\n"
"    pendingFlushes++;\n"
"    if (!flushPending) { flushPending = true; requestAnimationFrame(flushDisplay); }\n"
"  }\n"
"  function unpack(rgb) { return [(rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255, 255]; }\n"
"  function fillFb(x, y, w, h, rgb) {\n"
"    if (!fb32) return;\n"
"    x = Math.max(0, x); y = Math.max(0, y);\n"
"    w = Math.min(w, canvas.width - x); h = Math.min(h, canvas.height - y);\n"
"    if (w <= 0 || h <= 0) return;\n"
"    const c = rgbWord(rgb);\n"
"    for (let yy = 0; yy < h; yy++) {\n"
"      const p = (y + yy) * canvas.width + x;\n"
"      fb32.fill(c, p, p + w);\n"
"    }\n"
"  }\n"
"  function scrollFb(lines, rgb) {\n"
"    if (!fb32 || lines === 0) return;\n"
"    const row = canvas.width;\n"
"    const n = Math.min(Math.abs(lines), canvas.height);\n"
"    if (lines > 0) {\n"
"      fb32.copyWithin(0, n * row, canvas.height * row);\n"
"      fillFb(0, canvas.height - n, canvas.width, n, rgb);\n"
"    } else {\n"
"      fb32.copyWithin(n * row, 0, (canvas.height - n) * row);\n"
"      fillFb(0, 0, canvas.width, n, rgb);\n"
"    }\n"
"  }\n"
"  function blitFb(x, y, bw, bh, src) {\n"
"    if (!fb || bw <= 0 || bh <= 0) return;\n"
"    for (let yy = 0; yy < bh; yy++) {\n"
"      const dy = y + yy;\n"
"      if (dy < 0 || dy >= canvas.height) continue;\n"
"      let sx = 0, dx = x, copyW = bw;\n"
"      if (dx < 0) { sx = -dx; copyW += dx; dx = 0; }\n"
"      if (dx + copyW > canvas.width) copyW = canvas.width - dx;\n"
"      if (copyW <= 0) continue;\n"
"      fb.set(src.subarray((yy * bw + sx) * 4, (yy * bw + sx + copyW) * 4), (dy * canvas.width + dx) * 4);\n"
"    }\n"
"  }\n"
"  function blitRle332Fb(x, y, bw, bh, view, p, end) {\n"
"    if (!fb32 || bw <= 0 || bh <= 0) return {p:p, runs:0, pixels:0};\n"
"    let sx = 0, sy = 0, pixels = 0, runs = 0;\n"
"    const total = bw * bh;\n"
"    while (pixels < total) {\n"
"      if (p + 3 > end) return null;\n"
"      let run = view.getUint16(p, true); const c = rgb332Words[view.getUint8(p + 2)]; p += 3; runs++;\n"
"      if (run <= 0 || pixels + run > total) return null;\n"
"      while (run > 0) {\n"
"        const take = Math.min(run, bw - sx); const dy = y + sy;\n"
"        if (dy >= 0 && dy < canvas.height) {\n"
"          let dx = x + sx, copyW = take;\n"
"          if (dx < 0) { copyW += dx; dx = 0; }\n"
"          if (dx + copyW > canvas.width) copyW = canvas.width - dx;\n"
"          if (copyW > 0) {\n"
"            const q = dy * canvas.width + dx;\n"
"            fb32.fill(c, q, q + copyW);\n"
"          }\n"
"        }\n"
"        sx += take;\n"
"        if (sx >= bw) { sx = 0; sy++; }\n"
"        pixels += take; run -= take;\n"
"      }\n"
"    }\n"
"    return {p:p, runs:runs, pixels:pixels};\n"
"  }\n"
"  function drawFrame(buf) {\n"
"    if (buf.byteLength < 8) return;\n"
"    const t0 = performance.now();\n"
"    const view = new DataView(buf);\n"
"    const magic = String.fromCharCode(view.getUint8(0), view.getUint8(1), view.getUint8(2), view.getUint8(3));\n"
"    const w = view.getUint16(4, true);\n"
"    const h = view.getUint16(6, true);\n"
"    ensureSize(w, h);\n"
"    if (magic === 'FRMB') {\n"
"      const need = 8 + w * h * 4;\n"
"      if (buf.byteLength < need) { append('short FRMB ' + buf.byteLength + '/' + need); return; }\n"
"      const rgba = new Uint8ClampedArray(buf, 8, w * h * 4);\n"
"      fb.set(rgba);\n"
"      scheduleFlush();\n"
"      stats.FRMB++;\n"
"      stats.frames++; stats.bytes += buf.byteLength;\n"
"      note('display ' + w + 'x' + h, 'ok');\n"
"      debug('frame #' + stats.frames + ' FRMB bytes=' + buf.byteLength + ' decode=' + (performance.now() - t0).toFixed(2) + 'ms');\n"
"      return;\n"
"    }\n"
"    if (magic !== 'CMDS') { append('binary ' + magic + ' ' + buf.byteLength + ' bytes'); return; }\n"
"    let p = 8;\n"
"    const ops = [];\n"
"    while (p < buf.byteLength) {\n"
"      const op = view.getUint8(p++);\n"
"      if (op === 1 && p + 4 <= buf.byteLength) {\n"
"        const rgb = view.getUint32(p, true); p += 4;\n"
"        fillFb(0, 0, canvas.width, canvas.height, rgb);\n"
"        ops.push('CLS');\n"
"      } else if (op === 2 && p + 12 <= buf.byteLength) {\n"
"        const x = view.getInt16(p, true); const y = view.getInt16(p + 2, true);\n"
"        const rw = view.getUint16(p + 4, true); const rh = view.getUint16(p + 6, true);\n"
"        const rgb = view.getUint32(p + 8, true); p += 12;\n"
"        fillFb(x, y, rw, rh, rgb);\n"
"        ops.push('RECT:' + rw + 'x' + rh);\n"
"      } else if (op === 3 && p + 8 <= buf.byteLength) {\n"
"        const x = view.getInt16(p, true); const y = view.getInt16(p + 2, true);\n"
"        const rgb = view.getUint32(p + 4, true); p += 8;\n"
"        fillFb(x, y, 1, 1, rgb);\n"
"        ops.push('PIXEL');\n"
"      } else if (op === 4 && p + 6 <= buf.byteLength) {\n"
"        const lines = view.getInt16(p, true); const rgb = view.getUint32(p + 2, true); p += 6;\n"
"        scrollFb(lines, rgb);\n"
"        ops.push('SCROLL:' + lines);\n"
"      } else if (op === 5 && p + 8 <= buf.byteLength) {\n"
"        const x = view.getInt16(p, true); const y = view.getInt16(p + 2, true);\n"
"        const bw = view.getUint16(p + 4, true); const bh = view.getUint16(p + 6, true); p += 8;\n"
"        const n = bw * bh * 4;\n"
"        if (p + n > buf.byteLength) break;\n"
"        const rgba = new Uint8ClampedArray(buf, p, n);\n"
"        blitFb(x, y, bw, bh, rgba);\n"
"        p += n;\n"
"        ops.push('BLIT_RGBA:' + bw + 'x' + bh);\n"
"      } else if (op === 6 && p + 8 <= buf.byteLength) {\n"
"        const x = view.getInt16(p, true); const y = view.getInt16(p + 2, true);\n"
"        const bw = view.getUint16(p + 4, true); const bh = view.getUint16(p + 6, true); p += 8;\n"
"        const rle = blitRle332Fb(x, y, bw, bh, view, p, buf.byteLength);\n"
"        if (!rle) break;\n"
"        p = rle.p;\n"
"        ops.push('BLIT_RLE332:' + bw + 'x' + bh + ':runs=' + rle.runs);\n"
"      } else {\n"
"        append('unknown CMDS opcode ' + op); break;\n"
"      }\n"
"    }\n"
"    stats.CMDS++;\n"
"    stats.frames++; stats.bytes += buf.byteLength;\n"
"    scheduleFlush();\n"
"    note('display ' + canvas.width + 'x' + canvas.height, 'ok');\n"
"    debug('frame #' + stats.frames + ' CMDS bytes=' + buf.byteLength + ' decode=' + (performance.now() - t0).toFixed(2) + 'ms ops=' + ops.join(','));\n"
"  }\n"
"  function connect() {\n"
"    const scheme = location.protocol === 'https:' ? 'wss://' : 'ws://';\n"
"    ws = new WebSocket(scheme + location.host + '/__web_console/ws');\n"
"    ws.binaryType = 'arraybuffer';\n"
"    ws.onopen = () => {\n"
"      note('connected', 'ok'); append('socket open');\n"
"      ws.send(JSON.stringify({op:'hello', client:'browser', version:1}));\n"
"      ws.send(JSON.stringify({op:'status'}));\n"
"    };\n"
"    ws.onclose = () => { note('disconnected, retrying', 'err'); setTimeout(connect, 1000); };\n"
"    ws.onerror = () => note('socket error', 'err');\n"
"    ws.onmessage = ev => {\n"
"      if (ev.data instanceof ArrayBuffer) { drawFrame(ev.data); return; }\n"
"      try {\n"
"        const msg = JSON.parse(ev.data);\n"
"        if (msg.op === 'hello' || msg.op === 'status') note('connected: ' + msg.op, 'ok');\n"
"        append((msg.op || 'json') + ' ' + ev.data);\n"
"      } catch (e) { append('text ' + ev.data); }\n"
"    };\n"
"  }\n"
"  function inputFocused() {\n"
"    const el = document.activeElement;\n"
"    if (!el || el === document.body || el === canvas) return el === canvas;\n"
"    const tag = el.tagName;\n"
"    return !(tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || el.isContentEditable) && el.closest('main') !== null;\n"
"  }\n"
"  function mapKey(ev) {\n"
"    if ((ev.metaKey || ev.altKey) && !ev.ctrlKey) return -1;\n"
"    if (ev.key.length === 1) {\n"
"      if (ev.ctrlKey && !ev.altKey && !ev.metaKey) {\n"
"        const lower = ev.key.toLowerCase();\n"
"        if (lower >= 'a' && lower <= 'z') return lower.charCodeAt(0) - 96;\n"
"      }\n"
"      const code = ev.key.charCodeAt(0);\n"
"      return code < 256 ? code : -1;\n"
"    }\n"
"    if (ev.key === 'Tab' && ev.shiftKey) return 159;\n"
"    return Object.prototype.hasOwnProperty.call(specialKeys, ev.key) ? specialKeys[ev.key] : -1;\n"
"  }\n"
"  function sendKey(code) {\n"
"    if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({op:'key', code:code & 255}));\n"
"  }\n"
"  canvas.addEventListener('pointerdown', () => canvas.focus({preventScroll:true}));\n"
"  window.addEventListener('keydown', ev => {\n"
"    if (!inputFocused()) return;\n"
"    const code = mapKey(ev);\n"
"    if (code < 0) return;\n"
"    ev.preventDefault();\n"
"    sendKey(code);\n"
"  });\n"
"  canvas.focus({preventScroll:true});\n"
"  window.__webConsoleStats = stats;\n"
"  note('connecting'); connect();\n"
"})();\n";

static const web_console_asset_t assets[] = {
    { "/__web_console/", "text/html", index_html, sizeof(index_html) - 1u },
    { "/__web_console/index.html", "text/html", index_html, sizeof(index_html) - 1u },
    { "/__web_console/app.js", "application/javascript", app_js, sizeof(app_js) - 1u },
    { "/__web_console/style.css", "text/css", style_css, sizeof(style_css) - 1u },
};

static int path_equal_ignore_query(const char *a, const char *b) {
    size_t n = 0;
    while (a[n] && a[n] != '?') n++;
    return strlen(b) == n && memcmp(a, b, n) == 0;
}

const web_console_asset_t *web_console_asset_find(const char *path) {
    if (!path) return NULL;
    for (size_t i = 0; i < sizeof(assets) / sizeof(assets[0]); i++) {
        if (path_equal_ignore_query(path, assets[i].path)) return &assets[i];
    }
    return NULL;
}
