#!/usr/bin/env python3
"""Generate GNU-as include data for the pc386 boot-floppy stage2 loader."""

import argparse
import math
import struct
import sys

PT_LOAD = 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("elf")
    ap.add_argument("out")
    ap.add_argument("--kernel-lba", type=lambda s: int(s, 0), required=True)
    ns = ap.parse_args()

    data = open(ns.elf, "rb").read()
    if data[:4] != b"\x7fELF" or data[4] != 1 or data[5] != 1:
        raise SystemExit(f"{ns.elf}: expected little-endian ELF32")

    e_entry = struct.unpack_from("<I", data, 24)[0]
    e_phoff = struct.unpack_from("<I", data, 28)[0]
    e_phentsize = struct.unpack_from("<H", data, 42)[0]
    e_phnum = struct.unpack_from("<H", data, 44)[0]

    loads = []
    for i in range(e_phnum):
        off = e_phoff + i * e_phentsize
        p_type, p_offset, _vaddr, p_paddr, p_filesz, p_memsz, _flags, _align = struct.unpack_from("<IIIIIIII", data, off)
        if p_type != PT_LOAD:
            continue
        if p_offset % 512:
            raise SystemExit(f"{ns.elf}: PT_LOAD offset 0x{p_offset:x} is not sector aligned")
        if p_filesz > p_memsz:
            raise SystemExit(f"{ns.elf}: PT_LOAD filesz exceeds memsz")
        sectors = math.ceil(p_filesz / 512)
        loads.append((ns.kernel_lba + p_offset // 512, p_paddr, sectors, p_filesz, p_memsz))

    if not loads:
        raise SystemExit(f"{ns.elf}: no PT_LOAD segments")

    with open(ns.out, "w", encoding="ascii") as fp:
        fp.write("/* Generated by gen_floppy_load_plan.py. */\n")
        fp.write(f".set KERNEL_ENTRY, 0x{e_entry:08X}\n")
        fp.write(f".set LOAD_PLAN_COUNT, {len(loads)}\n")
        for lba, paddr, sectors, filesz, memsz in loads:
            fp.write(f"    .long {lba}, 0x{paddr:08X}, {sectors}, 0x{filesz:X}, 0x{memsz:X}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
